CostAllocationApp/ViewModels/ExportViewModel.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;

namespace CostAllocationApp.ViewModels
{
    public class ExportViewModel:BaseViewModel
    {
    }
}

CostAllocationApp/Controllers/ExportsController.cs
using System;
using System.Text;
using System.Collections.Generic;
using System.Linq;
using System.Net.Http;
using System.Web;
using System.Web.Mvc;
using CostAllocationApp.BLL;
using CostAllocationApp.ViewModels;
using OfficeOpenXml;
using OfficeOpenXml.Style;
using System.Drawing;
using CostAllocationApp.Dtos;
using System.Data;
using CostAllocationApp.Models;

namespace CostAllocationApp.Controllers
{
    public class ExportsController : Controller
    {
        private DepartmentBLL _departmentBLL = null;
        private ExportBLL _exportBLL = null;
        private SalaryBLL _salaryBLL = null;
        private ExplanationsBLL _explanationsBLL = null;
        private GradeBLL _gradeBll = null;
        private CommonMasterBLL _commonMasterBLL = null;
        private UnitPriceTypeBLL _unitPriceTypeBLL = null;
        private ExportDepartmentAllocationViewModel _exportDepartmentAllocationViewModel = null;
        private Utility _utility = new Utility();

        public ExportsController()
        {
            _departmentBLL = new DepartmentBLL();
            _exportBLL = new ExportBLL();
            _salaryBLL = new SalaryBLL();
            _explanationsBLL = new ExplanationsBLL();
            _gradeBll = new GradeBLL();
            _commonMasterBLL = new CommonMasterBLL();
            _unitPriceTypeBLL = new UnitPriceTypeBLL();
            _exportDepartmentAllocationViewModel = new ExportDepartmentAllocationViewModel();
        }
        // GET: Exports
        public FileResult ExportBySection(int sectionId = 0, string sectionName = "")
        {
            List<ForecastAssignmentViewModel> forecastAssignmentViewModels = new List<ForecastAssignmentViewModel>();
            using (var client = new HttpClient())
            {
                string uri = ""+_utility.Address+"/api/utilities/SearchForecastEmployee?employeeName=&sectionId=" + sectionId + "&departmentId=&inchargeId=&roleId=&explanationId=&companyId=&status=&year=";
                client.BaseAddress = new Uri(uri);
                //HTTP GET
                var responseTask = client.GetAsync("");
                responseTask.Wait();

                var result = responseTask.Result;
                if (result.IsSuccessStatusCode)
                {
                    var readTask = result.Content.ReadAsAsync<List<ForecastAssignmentViewModel>>();
                    readTask.Wait();

                    forecastAssignmentViewModels = readTask.Result;
                }
                else //web api sent error response 
                {
                    //log response status here..

                    forecastAssignmentViewModels = new List<ForecastAssignmentViewModel>();

                    // ModelState.AddModelError(string.Empty, "Server error. Please contact administrator.");
                }
            }
            string htmlTable = "";
            if (forecastAssignmentViewModels.Count > 0)
            {
                int i = 1;
                htmlTable = @"<!DOCTYPE html>
                <html>
                    <head>
                        <style>
                        #dev_placement {
                          border-collapse: collapse;
                          width: 50%;
                        }

                        #dev_placement td, #dev_placement th {
                          border: 1px solid #ddd;
                        }
                        </style>
                    </head>
                <body>

                <table id='dev_placement'>
                <thead>
                  <tr>
                    <th>No</th>
                    <th>FullName</th>
                    <th>Section</th>
                    <th>Department</th>
                    <th>Grade</th>
                    <th>UnitPrice</th>
                    <th>10</th>
                    <th>11</th>
                    <th>12</th>
                    <th>1</th>
                    <th>2</th>
                    <th>3</th>
                    <th>4</th>
                    <th>5</th>
                    <th>6</th>
                    <th>7</th>
                    <th>8</th>
                    <th>9</th>
                    <th>10</th>
                    <th>11</th>
                    <th>12</th>
                    <th>1</th>
                    <th>2</th>
                    <th>3</th>
                    <th>4</th>
                    <th>5</th>
                    <th>6</th>
                    <th>7</th>
                    <th>8</th>
                    <th>9</th>
                  </tr>
                </thead>
                <tbody>";
                foreach (var item in forecastAssignmentViewModels)
                {
                    string td = "";
                    string tdPoints = "";
                    if (item.forecasts.Count > 0)
                    {
                        foreach (var forecastItem in item.forecasts)
                        {
                            if (forecastItem.Points == 0)
                            {
                                td += $@"<td style='background-color:#808080;padding-right:20px;'> </td>";
                            }
                            else
                            {
                                td += $@"<td style='padding-right:20px;'>{forecastItem.Points}</td>";
                            }

                        }
                        foreach (var forecastItem in item.forecasts)
                        {
                            if (forecastItem.Points == 0)
                            {
                                tdPoints += $@"<td style='background-color:#808080;padding-right:20px;'> </td>";
                            }
                            else
                            {
                                //tdPoints += $@"<td style='padding-right:20px;text-align: right;'>{forecastItem.Total}</td>";
                                tdPoints += $@"<td style='text-align: right;'>{forecastItem.Total}</td>";
                            }

                        }
                    }
                    htmlTable += $@"
                          <tr>
                            <td>{i}</td>
                            <td>{item.EmployeeName}</td>
                            <td>{item.SectionName}</td>
                            <td>{item.DepartmentName}</td>
                            <td>{item.GradePoint}</td>
                            <td>{item.UnitPrice}</td>
                            {td}
                            {tdPoints}
                          </tr>
                    ";
                    i++;
                }
                htmlTable += @"
                 </tbody>
               </table>
                </body>
                </html> ";
            }
            UTF8Encoding uTF8Encoding = new UTF8Encoding();
            return File(uTF8Encoding.GetBytes(htmlTable), "application/vnd.ms-excel", sectionName + ".xls");
        }


        public ActionResult DataExportByDepartment()
        {
            return View(new ExportViewModel { Departments = _departmentBLL.GetAllDepartments() });
        }

        [HttpPost]
        public ActionResult DataExportByDepartment(int departmentId = 0)
        {
            List<ForecastAssignmentViewModel> forecastAssignmentViewModels = new List<ForecastAssignmentViewModel>();
            var _department = _departmentBLL.GetDepartmentByDepartemntId(departmentId);

            using (var client = new HttpClient())
            {
                string uri = "" + _utility.Address + "/api/utilities/SearchForecastEmployee?employeeName=&sectionId=&departmentId=" + departmentId + "&inchargeId=&roleId=&explanationId=&companyId=&status=&year=";
                client.BaseAddress = new Uri(uri);
                //HTTP GET
                var responseTask = client.GetAsync("");
                responseTask.Wait();

                var result = responseTask.Result;
                if (result.IsSuccessStatusCode)
                {
                    var readTask = result.Content.ReadAsAsync<List<ForecastAssignmentViewModel>>();
                    readTask.Wait();

                    forecastAssignmentViewModels = readTask.Result;
                }
                else //web api sent error response 
                {
                    //log response status here..

                    forecastAssignmentViewModels = new List<ForecastAssignmentViewModel>();

                    // ModelState.AddModelError(string.Empty, "Server error. Please contact administrator.");
                }
            }

            foreach (var forecastItem in forecastAssignmentViewModels)
            {
                if (forecastItem.CompanyName.ToLower() != "mw" || forecastItem.SectionName.ToLower() != "mw")
                {
                    forecastItem.GradePoint = "";
                }

            }


            using (var package = new ExcelPackage())
            {
                var sheet = package.Workbook.Worksheets.Add("Sheet1");

                sheet.Cells["A1"].Value = "Name";
                sheet.Cells["A1"].Style.Font.Bold = true;
                sheet.Cells["A1"].Style.Fill.PatternType = ExcelFillStyle.Solid;
                sheet.Cells["A1"].Style.Fill.BackgroundColor.SetColor(Color.SkyBlue);

                sheet.Cells["B1"].Value = "Section";
                sheet.Cells["B1"].Style.Font.Bold = true; ;
                sheet.Cells["B1"].Style.Fill.PatternType = ExcelFillStyle.Solid;
                sheet.Cells["B1"].Style.Fill.BackgroundColor.SetColor(Color.SkyBlue);

                sheet.Cells["C1"].Value = "Company";
                sheet.Cells["C1"].Style.Font.Bold = true;
                sheet.Cells["C1"].Style.Fill.PatternType = ExcelFillStyle.Solid;
                sheet.Cells["C1"].Style.Fill.BackgroundColor.SetColor(Color.SkyBlue);


                sheet.Cells["D1"].Value = "Department";
                sheet.Cells["D1"].Style.Font.Bold = true;

CostAllocationApp/Views/Exports/DataExportByAllocation.cshtml
@model CostAllocationApp.ViewModels.ExportViewModel
@{
    ViewBag.Title = "Data Export By Allocation";
}

<link rel="stylesheet" type="text/css" href="/Content/common.css" />
<link rel="stylesheet" type="text/css" href="/Content/data_export_by_allocation.css" />

<div class="content container-fluid">
    <div class="row">
        <div class="col-4">
            <div class="data_export_by_allocation">
                @using (Html.BeginForm("DataExportByAllocation", "Exports", FormMethod.Post))
                {
                    <div class="form-group">
                        <label for="department">Departments</label>
                        <select class="form-control" id="department" name="departmentId">
                            <option value="">Select Department</option>
                            @foreach (var item in Model.Departments)
                            {
                                <option value="@item.Id">@item.DepartmentName</option>
                            }
                        </select>
                    </div>
                    <div class="form-group">
                        <label for="explanation">Allocations</label>
                        <select class="form-control" id="explanation" name="explanationId"></select>
                    </div>
                    <button type="submit" class="btn btn-info" id="export">Export as Excel</button>
                }
            </div>
        </div>
    </div>
</div>

@section Scripts{

    <script type="text/javascript">
        $('#export').on('click', function (e) {
            var departmentValue = $('#department').val();
            var explanationValue = $('#explanation').val();
            if (departmentValue == undefined || departmentValue == null || departmentValue == "") {
                alert("Select Department");
                e.preventDefault();
            }
            if (explanationValue == undefined || explanationValue == null || explanationValue == "") {
                alert("Select Explanation");
                e.preventDefault();
            }
        });
        
        @* $('#department').on('change', function () {
            var departmentId = $(this).val();
            $.getJSON('/api/Utilities/GetAllExplanationsByDepartmentId?departmentId=' + departmentId)
                .done(function (data) {
                    $('#explanation').empty();
                    $('#explanation').append(`<option value=''>Select Allocation</option>`)
                    $.each(data, function (key, item) {
                        $('#explanation').append(`<option value='${item.Id}'>${item.ExplanationName}</option>`)
                    });
                });
        }); *@
        $('#department').on('change', function () {
            var departmentId = $(this).val();
            $.ajax({
                url: `/exports/GetAllExplanationsByDepartmentId/`,
                type: 'GET',
                dataType: 'json',        
                data:"departmentId="+departmentId,
                success: function (data) {
                    $('#explanation').empty();
                    $('#explanation').append(`<option value=''>select allocation</option>`)
                    $.each(data, function (key, item) {
                        $('#explanation').append(`<option value='${item.Id}'>${item.ExplanationName}</option>`)
                    });
                },
                error: function () {           
                }
            });   
        });
    </script>
    
}

CostAllocationApp/Views/Exports/DataExportByDepartment.cshtml
@model CostAllocationApp.ViewModels.ExportViewModel
@{
    ViewBag.Title = "Data Export By Department";
}

<link rel="stylesheet" type="text/css" href="/Content/common.css" />
<link rel="stylesheet" type="text/css" href="/Content/data_export_by_department.css" />

<div class="content container-fluid">
    <div class="row">
        <div class="col-4">
            <div class="data_export_by_department">
                @using (Html.BeginForm("DataExportByDepartment", "Exports", FormMethod.Post))
                {
                    <div class="form-group">
                        <label for="department">Select Department</label>
                        <select class="form-control" id="department" name="departmentId">
                            @foreach (var item in Model.Departments)
                            {
                                <option value="@item.Id">@item.DepartmentName</option>
                            }
                        </select>
                    </div>
                    <button type="submit" class="btn btn-info">Export as Excel</button>
                }
            </div>
        </div>
    </div>
</div>

@*@section Scripts{
    <script src="/Scripts/common.js"></script>
    <script src="/Scripts/companies.js"></script>
}*@