CostAllocationApp/Models/Forecast.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;

namespace CostAllocationApp.Models
{
    public class Forecast : Common
    {
        public int Id { get; set; }
        public int Year { get; set; }
        public int Month { get; set; }
        public decimal Points { get; set; }
        public decimal Total { get; set; }
        public int EmployeeAssignmentId { get; set; }
        public decimal Overtime { get; set; }

    }
}

CostAllocationApp/Controllers/Api/ForecastsController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Net;
using System.Net.Http;
using System.Web.Http;
using CostAllocationApp.Models;
using CostAllocationApp.BLL;

namespace CostAllocationApp.Controllers.Api
{
    public class ForecastsController : ApiController
    {
        ForecastBLL forecastBLL = null;
        public ForecastsController()
        {
            forecastBLL = new ForecastBLL();
        }
        [HttpGet]
        public IHttpActionResult CreateForecast(string data,string year,string assignmentId, string allocationId)
        {
            string[] monthData = data.Split(',');
            int tempYear = 0;
            int tempAssignmentId = 0;
            if (!Int32.TryParse(year,out tempYear))
            {
                return BadRequest("Something Went Wrong");
            }
            if (!Int32.TryParse(assignmentId, out tempAssignmentId))
            {
                return BadRequest("Something Went Wrong");
            }

            foreach (var item in monthData)
            {
                string[] temp = item.Split('_');
                Forecast forecast = new Forecast();
                decimal tempPoint = 0;
                if (Decimal.TryParse(temp[1],out tempPoint))
                {
                    if (tempPoint<0)
                    {
                        forecast.Points = 0;
                        forecast.Total = 0;
                        forecast.Overtime = 0;
                    }
                    else
                    {
                        forecast.Points = tempPoint;
                        forecast.Total = Convert.ToDecimal(temp[2]);
                        forecast.Overtime = Convert.ToDecimal(temp[3]);
                    }
                }
                else
                {
                    forecast.Points = tempPoint;
                    forecast.Total = 0;
                    forecast.Overtime = 0;
                }

                forecast.Month = Convert.ToInt32(temp[0]);
                forecast.Year = Convert.ToInt32(year);
                forecast.EmployeeAssignmentId = Convert.ToInt32(assignmentId);
                forecast.CreatedBy = "";
                forecast.CreatedDate = DateTime.Now;
                forecast.UpdatedBy = "";
                forecast.UpdatedDate = DateTime.Now;


                forecastBLL.UpdateEmployeesAssignmentFromForecst(allocationId,assignmentId);


                var result = forecastBLL.CheckAssignmentId(int.Parse(assignmentId),int.Parse(year), Convert.ToInt32(temp[0]));
                if (result==true)
                {
                    int resultEdit = forecastBLL.UpdateForecast(forecast);
                }
                else
                {
                    int resultSave = forecastBLL.CreateForecast(forecast);
                }

                
            }
            return Ok(true);

        }

        [HttpPost]
        public IHttpActionResult CreateForecastRecord(string data, string year, string assignmentId,string allocationId)
        {
            string[] monthData = data.Split(',');
            int tempYear = 0;
            int tempAssignmentId = 0;
            if (!Int32.TryParse(year, out tempYear))
            {
                return BadRequest("Something Went Wrong");
            }
            if (!Int32.TryParse(assignmentId, out tempAssignmentId))
            {
                return BadRequest("Something Went Wrong");
            }

            foreach (var item in monthData)
            {
                string[] temp = item.Split('_');
                Forecast forecast = new Forecast();
                decimal tempPoint = 0;
                if (Decimal.TryParse(temp[1], out tempPoint))
                {
                    if (tempPoint < 0)
                    {
                        forecast.Points = 0;
                        forecast.Total = 0;

                    }
                    else 
                    {
                        forecast.Points = tempPoint;
                        forecast.Total = Convert.ToDecimal(temp[2]);
                    }
                }
                else
                {
                    forecast.Points = tempPoint;
                    forecast.Total = 0;
                }

                forecast.Month = Convert.ToInt32(temp[0]);
                forecast.Year = Convert.ToInt32(year);
                forecast.EmployeeAssignmentId = Convert.ToInt32(assignmentId);
                forecast.CreatedBy = "";
                forecast.CreatedDate = DateTime.Now;
                forecast.UpdatedBy = "";
                forecast.UpdatedDate = DateTime.Now;

                var result = forecastBLL.CheckAssignmentId(int.Parse(assignmentId), int.Parse(year), Convert.ToInt32(temp[0]));
                if (result == true)
                {
                    int resultEdit = forecastBLL.UpdateForecast(forecast);
                }
                else
                {
                    int resultSave = forecastBLL.CreateForecast(forecast);
                }


            }
            return Ok(true);

        }
    }
}

CostAllocationApp/Controllers/ForecastsController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.IO;
using ExcelDataReader;
using System.Web.Mvc;
using System.Net.Http;
using CostAllocationApp.Dtos;
using CostAllocationApp.BLL;
using CostAllocationApp.ViewModels;
using CostAllocationApp.Models;
using CostAllocationApp.DAL;
using System.Data;

namespace CostAllocationApp.Controllers
{
    public class ForecastsController : Controller
    {

        EmployeeAssignmentBLL employeeAssignmentBLL = new EmployeeAssignmentBLL();
        UploadExcelBLL _uploadExcelBll = new UploadExcelBLL();
        UploadExcel _uploadExcel;
        char[] trimElements = { '\r', '\n', ' ' };
        SectionBLL sectionBLL = new SectionBLL();
        private DepartmentBLL _departmentBLL = new DepartmentBLL();
        private Utility _utility = new Utility();
        // GET: Forecasts
        public ActionResult CreateForecast(string departmentId = "")
        {
            //string departmentId = Request.QueryString["departmentId"];

            int tempDepartmentId = 0;
            Int32.TryParse(departmentId, out tempDepartmentId);
            if (tempDepartmentId == 0)
            {
                return RedirectToAction("Index", "Dashboard");
            }
            var singleDepartment = _departmentBLL.GetDepartmentByDepartemntId(tempDepartmentId);
            if (singleDepartment == null)
            {
                return RedirectToAction("Index", "Dashboard");
            }

            if (TempData["seccess"] != null)
            {
                ViewBag.Success = TempData["seccess"];
            }
            else
            {
                ViewBag.Success = null;
            }
            ForecastViewModal forecastViewModal = new ForecastViewModal
            {
                Departments = _departmentBLL.GetAllDepartments(),
                Department = singleDepartment,
            };
            ViewBag.ErrorCount = 0;
            return View(forecastViewModal);
        }

        //[NonAction]
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Index(HttpPostedFileBase uploaded_file, int upload_year,int department_id)
        {
            ForecastViewModal forecastViewModal = new ForecastViewModal
            {
                Departments = _departmentBLL.GetAllDepartments(),
                Department = _departmentBLL.GetDepartmentByDepartemntId(department_id)
            };

            TempData["seccess"] = null;
            Dictionary<int, int> check = new Dictionary<int, int>();
            if (ModelState.IsValid)
            {

                if ((uploaded_file != null && uploaded_file.ContentLength > 0) && upload_year > 0)
                {
                    // ExcelDataReader works with the binary Excel file, so it needs a FileStream
                    // to get started. This is how we avoid dependencies on ACE or Interop:
                    Stream stream = uploaded_file.InputStream;

                    IExcelDataReader reader = null;


                    //if (uploaded_file.FileName.EndsWith(".xls"))
                    //{
                    //    reader = ExcelReaderFactory.CreateBinaryReader(stream);
                    //}
                    if (uploaded_file.FileName.EndsWith(".xlsx"))
                    {
                        reader = ExcelReaderFactory.CreateOpenXmlReader(stream);
                    }
                    else
                    {
                        ModelState.AddModelError("File", "This file format is not supported");
                        ViewBag.ErrorCount = 1;
                        return View("CreateForecast", forecastViewModal);
                    }
                    //int fieldcount = reader.FieldCount;
                    //int rowcount = reader.RowCount;
                    //DataTable dt = new DataTable();
                    DataRow row;
                    DataTable dt_ = new DataTable();
                    try
                    {
                        int tempAssignmentId = 0;
                        string tempRow = "";
                        int tempYear = upload_year;
                        tempYear = 2022;
                        dt_ = reader.AsDataSet().Tables[0];
                        int rowcount = dt_.Rows.Count;

                        for (int i = 2; i < rowcount; i++)
                        {                            
                            _uploadExcel = new UploadExcel();
                            if (string.IsNullOrEmpty(dt_.Rows[i][0].ToString().Trim(trimElements)))
                            {
                                continue;
                            }
                            else
                            {
                                _uploadExcel.EmployeeName = dt_.Rows[i][0].ToString().Trim(trimElements);
                            }                            

                            int? sectionId = _uploadExcelBll.GetSectionIdByName(dt_.Rows[i][1].ToString().Trim(trimElements));
                            _uploadExcel.SectionId = sectionId == 0 ? null : sectionId;

                            int? companyId = _uploadExcelBll.GetCompanyIdByName(dt_.Rows[i][2].ToString().Trim(trimElements));
                            _uploadExcel.CompanyId = companyId == 0 ? null : companyId;

                            int? departmentId = _uploadExcelBll.GetDepartmentIdByName(dt_.Rows[i][3].ToString().Trim(trimElements));
                            _uploadExcel.DepartmentId = departmentId == 0 ? null : departmentId;

                            //allocation
                            int? explanationId = _uploadExcelBll.GetExplanationIdByName(dt_.Rows[i][6].ToString().Trim(trimElements));
                            _uploadExcel.ExplanationId = explanationId == 0 ? null : explanationId;
                            
                            decimal tempUnitPrice = 0;
                            decimal.TryParse(dt_.Rows[i][5].ToString(), out tempUnitPrice);

                            string tempUnitPrice2 = dt_.Rows[i][5].ToString();
                            string tempGradePoint = dt_.Rows[i][4].ToString();
                            UploadExcel _salary = new UploadExcel();
                            if (tempUnitPrice > 0)
                            {
                                //int? gradeId = _uploadExcelBll.GetGradeIdByUnitPrice(tempUnitPrice.ToString());
                                //_uploadExcel.GradeId = gradeId == 0 ? null : gradeId;
                                _uploadExcel.GradeId = null;
                                _uploadExcel.UnitPrice = tempUnitPrice;
                            }
                            else if (!string.IsNullOrEmpty(dt_.Rows[i][4].ToString()))
                            {
                                _salary = _uploadExcelBll.GetGradeIdByGradePoints(dt_.Rows[i][4].ToString());
                                _uploadExcel.GradeId = _salary.GradeId;

                                GradeUnitPriceType _salaryType = new GradeUnitPriceType();
                                if (!string.IsNullOrEmpty(_uploadExcel.GradeId.ToString()) && !string.IsNullOrEmpty(_uploadExcel.DepartmentId.ToString()))
                                {
                                    _salaryType = _uploadExcelBll.GetGradeUnitPriceType(_uploadExcel.GradeId, _uploadExcel.DepartmentId,2022,1);
                                    _uploadExcel.GradeId = _salaryType.Id;
                                    _uploadExcel.UnitPrice = Convert.ToDecimal(_salaryType.GradeLowPoints) ;
                                }
                                else
                                {
                                    _uploadExcel.GradeId = null;
                                    _uploadExcel.UnitPrice = 0;
                                }
                                //if(!string.IsNullOrEmpty(_salary.GradeHighPoints)){
                                //    _uploadExcel.UnitPrice = Convert.ToDecimal(_salary.GradeHighPoints);
                                //}else{
                                //    _uploadExcel.UnitPrice = 0;
                                //}                                
                            }
                            else
                            {
                                _uploadExcel.GradeId = null;
                                _uploadExcel.UnitPrice = 0;
                            }                           
                            
                            var assignmentViewModels = employeeAssignmentBLL.GetEmployeesByName(_uploadExcel.EmployeeName);
                            if (assignmentViewModels.Count > 0)
                            {
                                CreateAssignmentForExcelUpload(_uploadExcel, i, assignmentViewModels.Count);
                                tempAssignmentId = employeeAssignmentBLL.GetLastId();
                            }
                            else
                            {
                                //CreateAssignmentForExcelUpload(dt_, i);
                                CreateAssignmentForExcelUpload(_uploadExcel, i);
                                tempAssignmentId = employeeAssignmentBLL.GetLastId();
                            }

                            decimal octInput = 0;
                            decimal octOver = 0;
                            decimal.TryParse(dt_.Rows[i][7].ToString(), out octInput);
                            decimal.TryParse(dt_.Rows[i][33].ToString(), out octOver);

                            decimal novInput = 0;
                            decimal novOver = 0;
                            decimal.TryParse(dt_.Rows[i][8].ToString(), out novInput);
                            decimal.TryParse(dt_.Rows[i][34].ToString(), out novOver);

                            decimal decInput = 0;
                            decimal decOver = 0;

CostAllocationApp/Views/Forecasts/CreateForecast.cshtml
@model CostAllocationApp.ViewModels.ForecastViewModal

@{
    ViewBag.Title = "Create Forecast";
}
@section Styles {
    <link href="/Content/common.css" rel="stylesheet" type="text/css" />
    <link href="/Content/bootstrap-multiselect.css" rel="stylesheet" type="text/css" />
    <link href="/Content/forecast_ver04.css" rel="stylesheet" type="text/css" />  
    <link href="/Content/namelist-responsive.css" rel="stylesheet" type="text/css" />      
}

<div class="content container-fluid" style="position:relative">
    <!-- Page Header -->
    <div class="page-header" id="data_import">
        <div class="row align-items-center">
            <div class="col">
                <h5>Forecast Creation</h5>
            </div>
        </div>
        <div class="row">
            @*<div class="col">
                <a href="/Home/Index"><i class="fa fa-upload" aria-hidden="true"></i> Upload Excel</a>
            </div>*@

            <div class="col">
                @using (Html.BeginForm("Index", "Forecasts", null, FormMethod.Post, new { enctype = "multipart/form-data", @class = "form-inline" }))
                {
                <div class="form-group mb-2">
                    <input type="file" class="form-control-file" name="uploaded_file">
                    <input type="hidden" value="@Model.Department.Id" name="department_id" />
                </div>
                    
                    <div class="form-group mx-sm-3 mb-2">
                        <select id="inputState" class="form-control" name="upload_year">
                            <option value="0">Select Year</option>
                            <option value="2022">2022</option>
                        </select>
                    </div>
                    <button type="submit" class="btn btn-success mb-2" id="import_data_btn"><i class="fa fa-upload" aria-hidden="true"></i> Upload Excel</button>
                    @Html.AntiForgeryToken()


                }
                @if ((Int32)ViewBag.ErrorCount > 0)
                {
                    <div class="alert alert-danger col-4">
                        @Html.ValidationSummary()
                    </div>
                }
                @if (ViewBag.Success != null)
                {
                    <div class="alert alert-success col-4">
                        @ViewBag.Success
                    </div>
                }
            </div>
        </div>        
    </div>
    
    <!-- /Page Header -->
    <div class="row">       
        <div class="col-md-12">
            <section class="container" tabIndex="1">
                <div>
                    <table id="forecast_search">
                        <thead id="forecast_search_thead">
                            <tr>
                                <th>Name</th>
                                <th>Section</th>
                                <th>Company</th>
                                <th>Department</th>
                                <th>Allocation</th>                                
                                <th>Period</th>
                            </tr>                            
                        </thead>
                        <tbody id="forecast_search_tbody">                            
                            <tr>
                                <th class="namelist_td name">氏名(Name)</th>
                                <th class="namelist_td section">
                                    <div class="form-group mb-0">
                                        <div class="col-sm-10">
                                            <select id="section_multi_search" name="multiselect[]" multiple="multiple"></select>
                                        </div>
                                    </div>
                                </th>
                                <th class="namelist_td company">
                                    <div class="form-group mb-0">
                                        <div class="col-sm-10">
                                            <select id="company_multi_search" name="multiselect[]" multiple="multiple"></select>
                                        </div>
                                    </div>
                                </th>
                                <th class="namelist_td department">
                                    <div class="form-group mb-0">
                                        <div class="col-sm-10">
                                            <input type="text" value="@Model.Department.DepartmentName" readonly="" id="dept_multi_search">
                                            @* <select id="dept_multi_search" name="multiselect[]" multiple="multiple"></select> *@
                                        </div>
                                    </div>
                                </th>
                                <th class="namelist_td allocation">
                                    <div class="form-group mb-0">
                                        <div class="col-sm-10">
                                            <select id="allocation_multi_search" name="multiselect[]" multiple="multiple"></select>
                                        </div>
                                    </div>
                                </th>
                                <th class="namelist_td period">
                                    <div class="form-group mb-0">
                                        <div class="col-sm-10">
                                            <select id="period_multi_search" name="multiselect[]" multiple="multiple"></select>
                                        </div>
                                    </div>
                                </th>
                            </tr>                            
                            <tr>
                                <td colspan="5"></td>
                                <td>
                                    <a href="javascript:void(0);" class="" id="forecast_search_button">Search</a>
                                </td>
                            </tr>
                        </tbody>
                    </table>
                </div>
            </section>

            <div class="row">
                <div class="col-md-12">
                    <div class="forecast">
                        <div id="loading" style="display:none;position:absolute;left:0;top:-147px;  width:100%;height:100%;">
                            <center>
                                <img src="~/img/forecast_loader.gif" height="250" width="250" style="margin-top:200px;">
                                <br>
                                <strong>Please wait a moment...</strong>
                                <br>
                                <br>
                            </center>
                        </div>
                        <table class="" id="forecast_table">
                            <thead></thead>
                            <tbody></tbody>
                        </table>
                        <div class="add_name_tbl_2_btn">
                            <a href="javascript:void(0);" class="" id="cancel_forecast" onclick="onCancel()" style="display:none;">Cancel</a>
                            <a href="javascript:void(0);" class="" id="save_forecast" onclick="onSave(event)" style="display:none;">Save</a>
                        </div>
                    </div>
                </div>
            </div>
        </div>
    </div>
</div>

<input type="hidden" id="hidSectionId" />
<input type="hidden" id="hidDepartmentId" />
<input type="hidden" id="hidInChargeId" />
<input type="hidden" id="hidRoleId" />
<input type="hidden" id="hidExplanationId" />
<input type="hidden" id="hidCompanyid" />

<input type="hidden" id="hid_departmentId" value="@Model.Department.Id"/>

@section Scripts{

    <script src="/Scripts/bootstrap-3.3.2.min.js"></script>
    <script src="/Scripts/common.js"></script>
    <script src="/Scripts/forecast_ver04.js"></script>
    @* <script src="/Scripts/namelist_modal_registrations.js"></script> *@
    <script src="/Scripts/bootstrap-multiselect.js"></script>


    <script>
        $(document).ready(function () {
            $("table1").DataTable();
        });
        function bs_input_file() {
            $(".input-file").before(
                function () {
                    if (!$(this).prev().hasClass('input-ghost')) {
                        var element = $("<input type='file' id='dataFile' name='upload' class='input-ghost' style='visibility:hidden; height:0'>");
                        element.attr("name", $(this).attr("name"));
                        element.change(function () {
                            element.next(element).find('input').val((element.val()).split('\\').pop());
                        });
                        $(this).find("button.btn-choose").click(function () {
                            element.click();
                        });
                        $(this).find("button.btn-reset").click(function () {
                            element.val(null);
                            $(this).parents(".input-file").find('input').val('');
                        });
                        $(this).find('input').css("cursor", "pointer");
                        $(this).find('input').mousedown(function () {
                            $(this).parents('.input-file').prev().click();
                            return false;
                        });
                        return element;
                    }
                }
            );
        }

        function clear() {
            var input = $("#dataFile").val('');
        };
        $(function () {
            clear();
            bs_input_file();
        });
    </script>
}